# Generated by Django 4.0.2 on 2022-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloBD', '0002_tour_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%y')),
            ],
        ),
    ]
