# Generated by Django 4.0.2 on 2022-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloBD', '0003_gallery_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulerPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('des', models.TextField(default='give the describtion')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%y')),
            ],
        ),
    ]
